# Channel Rewards for Apex Legends
conditions:
  obsScene: Gaming Apex
rewards:
  - Fire Away
  - Jump
triggers:
  redemption:
    Fire Away:
      actions:
        - notification:
            header: Pew Pew
            text: "{{user}} is giving away your position"
            color: "{{userColor}}"
        - mouseButton:
            button: 1
            time: 1.5
    Jump:
      actions:
        - notification:
            header: Jump
            text: "{{user}} has jumped!"
            color: "{{userColor}}"
        - pressKey:
            key: space
