conditions:
  obsScene: "Gaming AOE3"
rewards:
  - 1v1 With Me!!!
  - 2v2 With Me!!!
triggers:
  chat:
    "1":
      actions:
        - tts: Yes
    "2":
      actions:
        - tts: No
    "15":
      actions:
        - tts: Wololo
    "21":
      actions:
        - tts: Ha ha ha hahhhhhh
    "!villager":
      actions:
        - tts: Train a villager
    "!retreat":
      actions:
        - tts: Retreat
    "!raidvillagers":
      actions:
        - tts: Go raid villagers
    "!raid":
      actions:
        - tts: You are being raided
    "!house":
      actions:
        - tts: Build a house
    "!shipment":
      actions:
        - tts: Send a shipment
    "!siegedance":
      actions:
        - tts: womp womp devs nerfed it
    "!mlga":
      actions:
        - tts: Make Lakota Great Again
    "!drongo":
      actions:
        - tts: handsome and very good at microing civ select
    "!ping":
      actions:
        - pressKey:
            time: 1
            key: p
      sync: false
  redemption:
    1v1 With Me!!!:
      sync: true
      actions:
        - notification:
            header: 1v1 With {{channel}}
            text: "{{user}} is challenging {{channel}} to a 1v1"
            color: "{{userColor}}"
        - tts: "{{User}} is challenging {{channel}} to a 1v1. Prepare to duel!"
    2v2 With Me!!!:
      sync: true
      actions:
        - notification:
            header: 2v2 With {{channel}}
            text: "{{User}} is challenging {{channel}} to a 2v2"
            color: "{{userColor}}"
        - oneOf:
            - - sound: aoeUke.mp3
            - - sound: aoeTrumpet.mp3
        - tts: "{{user}} is challenging {{channel}} to a 2v2. Prepare to duel!"