name: Gobal
variables:
  pushups:
    default: 0
  pullups:
    default: 0
  userhue:
    default: 0
triggers:
  modchat:
    "!scene":
      actions:
        - obsScene: "{{ argString }}"
    "!zelda":
      actions:
        - import: ./sequences/zeldachest.yaml
    "!raid":
      actions:
        - import: ./sequences/sirenalert.yaml
  chat:
    "!scene":
      actions:
        - tts: Change the Scene
          "!lights": null
        - say: "You can change the lights on FitzBro's stream! Try it out: '!red',
            '!purple', '!blue', You can also pick a color with '!hue <number>'."
    "!sounds":
      oneOf:
        - - say: "Try out a sound such as: '!woo', '!goodnews', '!rimshot', or '!scream'."
        - - say: "Try out a sound such as: '!secret', '!getyourshit', '!insult', or
              '!loser'."
        - - say: "Try out a sound such as: '!ehhghh', '!yeet', '!womp', or '!figure'."
        - - say: "Try out a sound such as: '!fubar', '!murder', '!suspense', or '!salt'."
        - - say: "Try out a sound such as: '!math', '!yep', '!unacceptable', or '!cando'."
    "!keyboard":
      - say: SteelSeries Apex 7 TKL Compact Mechanical Gaming Keyboard | Blue Switches
      - say: Enter your discord here!
    "!cookie":
      - say: Join us for 🍪 Cookie Quest! 🍪 on Sundays at 3:30pm EST
      - say: "Alfajores: Argentinian Dulce De Leche Sandwich Cookie!"
    imports:
      - ./triggers/sounds.yaml
      - ./triggers/colors.yaml
  follow:
    actions:
      - import: ./sequences/zeldachest.yaml
      - notification:
          header: New Follower
          text: Thanks for following {{user}}
          color: "{{ userColor }}"
  subscribe:
    "0":
      actions:
        - import: ./sequences/recorderfox.yaml
        - notification:
            header: New Subscriber
            text: Thanks for subscribing {{user}}
            color: "{{ userColor }}"
  raid:
    "2":
      actions:
        - notification:
            header: Raid Incoming
            text: "!!! {{ user }} is Raiding !!!"
        - import: ./sequences/sirenalert.yaml
        - notification:
            header: Raid Arrived
            text: Welcome to all {{number}} viewers from {{user}}'s channel
  bits:
    "0":
      actions:
        - sound: ./sounds/cashRegister.mp3
        - notification:
            header: Bits!
            text: Thanks {{ user }} for the bits!
        - tts: "{{ filteredMessage }}"
  redemption:
    Text To Speech:
      - tts: "{{ filteredMessage }}"
    Push Up Time:
      - notification:
          header: Push Up Time
          text: "{{user}} demands pushups."
          color: "{{ userColor }}"
      - variable:
          name: pushups
          offset: 25
    Pull Up Time:
      actions:
        - tts: Stop and Do Pullups.
        - notification:
            header: Pull Up Time
            text: "{{user}} demands pullups."
            color: "{{ userColor }}"
        - variable:
            name: pullups
            offset: 6
    Police!:
      actions:
        - import: ./sequences/police.yaml
        - notification:
            header: Police
            text: "{{user}} says open up!"
            color: "{{ userColor }}"
rewards:
  - Police!
