conditions:
  obsScene: Lobby AOE3
rewards:
  - Lakota Coaching w/FitzBro
  - Pick a Civ
triggers:
  chat:
    "1":
      actions:
        - tts: Yes
    "2":
      actions:
        - tts: No
    "15":
      actions:
        - tts: Wololo
    "21":
      actions:
        - tts: Ha ha ha hahhhhhh
    "31":
      actions:
        - sound: /sounds/trumpet.mp3
    "!villager":
      actions:
        - tts: Train a villager
    "!retreat":
      actions:
        - tts: Retreat
    "!raidvillagers":
      actions:
        - tts: Go raid villagers
    "!raid":
      actions:
        - tts: You are being raided
    "!house":
      actions:
        - tts: Build a house
    "!shipment":
      actions:
        - tts: Send a shipment
    "!siegedance":
      actions:
        - tts: womp womp devs nerfed it
    "!mlga":
      actions:
        - tts: Make Lakota Great Again
    "!drongo":
      actions:
        - tts: handsome and very good at microing civ select
    "!tashunke":
      actions:
        - pressKey:
            time: 1
            key: "5"
        - pressKey:
            time: 0
            key: r
          beforeDelay: 1
      sync: false
  redemption:
    "Lakota Coaching w/{{channel}}":
      sync: true
      actions:
        - notification:
            header: Lakota Coaching w/{{channel}} Activated
            text: "{{user}} is ready to learn!"
            color: "{{userColor}}"
        - tts: "{{user}} has redeemed Lakota coaching with {{channel}}"
    Pick a Civ:
      sync: true
      actions:
        - notification:
            header: Pick a Civ
            text: "{{user}} has picked a Civ: {{message}}"
            color: "{{userColor}}"
        - tts: "{{user}} has picked a Civ: {{message}}"