name: Minecraft
conditions:
  obsScene: Gaming Minecraft
rewards:
  - Sheepify Me
  - Slow Down There
  - Boom Boom
  - Woops I Spilled
  - Butter Fingers
triggers:
  redemption:
    "Sheepify Me":
      actions:
        - notification:
            header: Sheep
            text: "{{user}} wants to be a sheep"
            color: "{{userColor}}"
        - mineCmd: "execute at @a[name=LordTocs] run summon sheep ~ ~ ~ {CustomName: \"\\\"{{user}}\\\"\"}"
    "Boom Boom":
      actions:
        - notification:
            header: Creeper
            text: "{{user}} sends their regards"
            color: "{{userColor}}"
        - mineCmd: "execute at @a[name=LordTocs] run summon creeper ~ ~3 ~ {CustomName: \"\\\"{{user}}\\\"\"}"
    "Slow Down There":
      actions:
        - notification:
            header: Slowness
            text: "{{user}} wants you to slow down"
            color: "{{userColor}}"
        - mineCmd: "effect give lordtocs slowness 10 1"
    "Woops I Spilled":
      actions:
          - notification:
              header: Woops
              text: "{{user}} spilled some water"
              color: "{{userColor}}"
          - mineCmd: "execute at @a[name=LordTocs] run setblock ~ ~ ~ water keep"
    "Butter Fingers":
      actions:
        - pressKey:
            key: q

