name: Wheel
conditions:
  obsScene: "Civ Wheel"
rewards:
  - Spin the Wheel!
triggers:
  redemption:
    "Spin the Wheel!":
      actions:
        - websocket:
            wheel:
              spin: 10