name: Build / Release

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: "Install Node Packages"
        run: "npm install"
      #- name: "Rebuild for Electron"
      #  run: "npm run rebuild"
      - name: "Build"
        run: "npm run electron:build -- -p always"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VUE_APP_MIXPANEL_PROJECT_TOKEN: ${{ secrets.MIXPANEL_PROJECT_TOKEN }}
